getgenv().RHub = getgenv().RHub or {}


local Players = game:GetService("Players")
local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")


local RRR = Instance.new("ScreenGui")
RRR.Name = "RRR"
RRR.Parent = playerGui

getgenv().RHub.Gui = RRR

    local Container = Instance.new("Frame")
    Container.Name = "Container"
    Container.AnchorPoint = Vector2.new(0, 0)
    Container.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    Container.BackgroundTransparency = 1
    Container.BorderColor3 = Color3.fromRGB(0, 0, 0)
    Container.BorderSizePixel = 1
    Container.Position = UDim2.new(0, 0, 0, 0)
    Container.Rotation = 0
    Container.Size = UDim2.new(1, 0, 1, 0)
    Container.SizeConstraint = Enum.SizeConstraint.RelativeXY
    Container.Visible = true
    Container.ZIndex = 1
    Container.LayoutOrder = 0
    Container.Style = Enum.FrameStyle.Custom
    Container.Parent = RRR

        local Drag = Instance.new("ImageLabel")
        Drag.Name = "Drag"
        Drag.AnchorPoint = Vector2.new(0, 0)
        Drag.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Drag.BackgroundTransparency = 1
        Drag.BorderColor3 = Color3.fromRGB(0, 0, 0)
        Drag.BorderSizePixel = 0
        Drag.Position = UDim2.new(0.26356589794158936, 0, 0.27697262167930603, 0)
        Drag.Rotation = 0
        Drag.Size = UDim2.new(0.47028422355651855, 0, 0.46537843346595764, 0)
        Drag.SizeConstraint = Enum.SizeConstraint.RelativeXY
        Drag.Visible = true
        Drag.ZIndex = 1
        Drag.LayoutOrder = 0
        Drag.Image = "rbxassetid://132146341566959"
        Drag.ImageColor3 = Color3.fromRGB(255, 255, 255)
        Drag.ImageTransparency = 0
        Drag.ScaleType = Enum.ScaleType.Stretch
        Drag.SliceCenter = "0, 0, 0, 0"
        Drag.SliceScale = 1
        Drag.TileSize = UDim2.new(1, 0, 1, 0)
        Drag.Parent = Container

            local Main = Instance.new("ImageLabel")
            Main.Name = "Main"
            Main.AnchorPoint = Vector2.new(0, 0)
            Main.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
            Main.BackgroundTransparency = 1
            Main.BorderColor3 = Color3.fromRGB(0, 0, 0)
            Main.BorderSizePixel = 0
            Main.Position = UDim2.new(0.15249735116958618, 0, 0.11826489120721817, 0)
            Main.Rotation = 0
            Main.Size = UDim2.new(0.807692289352417, 0, 0.8525073528289795, 0)
            Main.SizeConstraint = Enum.SizeConstraint.RelativeXY
            Main.Visible = true
            Main.ZIndex = 1
            Main.LayoutOrder = 0
            Main.Image = "rbxassetid://116118555895648"
            Main.ImageColor3 = Color3.fromRGB(255, 255, 255)
            Main.ImageTransparency = 0.20000000298023224
            Main.ScaleType = Enum.ScaleType.Stretch
            Main.SliceCenter = "0, 0, 0, 0"
            Main.SliceScale = 1
            Main.TileSize = UDim2.new(1, 0, 1, 0)
            Main.Parent = Drag

                local Misc = Instance.new("ScrollingFrame")
                Misc.Name = "Misc"
                Misc.AnchorPoint = Vector2.new(0, 0)
                Misc.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                Misc.BackgroundTransparency = 1
                Misc.BorderColor3 = Color3.fromRGB(0, 0, 0)
                Misc.BorderSizePixel = 0
                Misc.Position = UDim2.new(0, 0, -1.2386657033403026e-07, 0)
                Misc.Rotation = 0
                Misc.Size = UDim2.new(1, 0, 0.98630291223526, 0)
                Misc.SizeConstraint = Enum.SizeConstraint.RelativeXY
                Misc.Visible = false
                Misc.ZIndex = 1
                Misc.LayoutOrder = 0
                Misc.BottomImage = "rbxasset://textures/ui/Scroll/scroll-bottom.png"
                Misc.CanvasPosition = Vector2.new(0, 0)
                Misc.CanvasSize = UDim2.new(0, 0, 0, 0)
                Misc.ElasticBehavior = Enum.ElasticBehavior.WhenScrollable
                Misc.HorizontalScrollBarInset = Enum.ScrollBarInset.None
                Misc.MidImage = "rbxasset://textures/ui/Scroll/scroll-middle.png"
                Misc.ScrollBarImageColor3 = Color3.fromRGB(0, 0, 0)
                Misc.ScrollBarImageTransparency = 0
                Misc.ScrollBarThickness = 5
                Misc.ScrollingDirection = Enum.ScrollingDirection.XY
                Misc.ScrollingEnabled = true
                Misc.TopImage = "rbxasset://textures/ui/Scroll/scroll-top.png"
                Misc.VerticalScrollBarInset = Enum.ScrollBarInset.None
                Misc.VerticalScrollBarPosition = Enum.VerticalScrollBarPosition.Right
                Misc.Parent = Main

                    local UIListLayout = Instance.new("UIListLayout")
                    UIListLayout.Name = "UIListLayout"
                    UIListLayout.FillDirection = Enum.FillDirection.Vertical
                    UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
                    UIListLayout.Padding = UDim.new(0.009999999776482582, 0)
                    UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
                    UIListLayout.VerticalAlignment = Enum.VerticalAlignment.Top
                    UIListLayout.Wraps = false
                    UIListLayout.Parent = Misc

                    local M = Instance.new("Frame")
                    M.Name = "M"
                    M.AnchorPoint = Vector2.new(0, 0)
                    M.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                    M.BackgroundTransparency = 0.800000011920929
                    M.BorderColor3 = Color3.fromRGB(0, 0, 0)
                    M.BorderSizePixel = 0
                    M.Position = UDim2.new(0, 0, 0, 0)
                    M.Rotation = 0
                    M.Size = UDim2.new(1, 0, 0.273341566324234, 0)
                    M.SizeConstraint = Enum.SizeConstraint.RelativeXY
                    M.Visible = true
                    M.ZIndex = 1
                    M.LayoutOrder = 0
                    M.Style = Enum.FrameStyle.Custom
                    M.Parent = Misc

                        local UICorner = Instance.new("UICorner")
                        UICorner.Name = "UICorner"
                        UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                        UICorner.Parent = M

                        local CheatName = Instance.new("TextLabel")
                        CheatName.Name = "CheatName"
                        CheatName.AnchorPoint = Vector2.new(0, 0)
                        CheatName.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.BackgroundTransparency = 12
                        CheatName.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.BorderSizePixel = 0
                        CheatName.Position = UDim2.new(0.011904762126505375, 0, 0, 0)
                        CheatName.Rotation = 0
                        CheatName.Size = UDim2.new(0.2394559234380722, 0, 1, 0)
                        CheatName.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        CheatName.Visible = true
                        CheatName.ZIndex = 1
                        CheatName.LayoutOrder = 0
                        CheatName.Font = Enum.Font.SourceSans
                        CheatName.Text = "PowerShot"
                        CheatName.TextColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.TextScaled = true
                        CheatName.TextSize = 14
                        CheatName.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.TextStrokeTransparency = 1
                        CheatName.TextWrapped = true
                        CheatName.TextXAlignment = Enum.TextXAlignment.Center
                        CheatName.TextYAlignment = Enum.TextYAlignment.Center
                        CheatName.Parent = M

                        local PowerValue = Instance.new("TextBox")
                        PowerValue.Name = "PowerValue"
                        PowerValue.AnchorPoint = Vector2.new(0, 0)
                        PowerValue.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                        PowerValue.BackgroundTransparency = 0.800000011920929
                        PowerValue.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        PowerValue.BorderSizePixel = 0
                        PowerValue.Position = UDim2.new(0.2789115607738495, 0, 0.19929662346839905, 0)
                        PowerValue.Rotation = 0
                        PowerValue.Size = UDim2.new(0.3401360511779785, 0, 0.5861665606498718, 0)
                        PowerValue.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        PowerValue.Visible = true
                        PowerValue.ZIndex = 1
                        PowerValue.LayoutOrder = 0
                        PowerValue.Font = Enum.Font.SourceSans
                        PowerValue.Text = ""
                        PowerValue.TextColor3 = Color3.fromRGB(255, 0, 4)
                        PowerValue.TextScaled = true
                        PowerValue.TextSize = 14
                        PowerValue.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        PowerValue.TextStrokeTransparency = 1
                        PowerValue.TextWrapped = true
                        PowerValue.TextXAlignment = Enum.TextXAlignment.Center
                        PowerValue.TextYAlignment = Enum.TextYAlignment.Center
                        PowerValue.ClearTextOnFocus = true
                        PowerValue.MultiLine = false
                        PowerValue.PlaceholderText = "170-230"
                        PowerValue.PlaceholderColor3 = Color3.fromRGB(207, 207, 207)
                        PowerValue.Parent = M

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                            UICorner.Parent = PowerValue

                        local PowerShot = Instance.new("TextButton")
                        PowerShot.Name = "PowerShot"
                        PowerShot.AnchorPoint = Vector2.new(0, 0)
                        PowerShot.BackgroundColor3 = Color3.fromRGB(229, 0, 4)
                        PowerShot.BackgroundTransparency = 0
                        PowerShot.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        PowerShot.BorderSizePixel = 0
                        PowerShot.Position = UDim2.new(0.7363945841789246, 0, 0.2579132914543152, 0)
                        PowerShot.Rotation = 0
                        PowerShot.Size = UDim2.new(0.18027210235595703, 0, 0.48065656423568726, 0)
                        PowerShot.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        PowerShot.Visible = true
                        PowerShot.ZIndex = 1
                        PowerShot.LayoutOrder = 0
                        PowerShot.Font = Enum.Font.SourceSans
                        PowerShot.Text = "OFF"
                        PowerShot.TextColor3 = Color3.fromRGB(255, 255, 255)
                        PowerShot.TextScaled = true
                        PowerShot.TextSize = 14
                        PowerShot.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        PowerShot.TextStrokeTransparency = 1
                        PowerShot.TextWrapped = true
                        PowerShot.TextXAlignment = Enum.TextXAlignment.Center
                        PowerShot.TextYAlignment = Enum.TextYAlignment.Center
                        PowerShot.AutoButtonColor = true
                        PowerShot.Parent = M

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(5, 0)
                            UICorner.Parent = PowerShot

                    local M = Instance.new("Frame")
                    M.Name = "M"
                    M.AnchorPoint = Vector2.new(0, 0)
                    M.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                    M.BackgroundTransparency = 0.800000011920929
                    M.BorderColor3 = Color3.fromRGB(0, 0, 0)
                    M.BorderSizePixel = 0
                    M.Position = UDim2.new(0, 0, 0, 0)
                    M.Rotation = 0
                    M.Size = UDim2.new(1, 0, 0.273341566324234, 0)
                    M.SizeConstraint = Enum.SizeConstraint.RelativeXY
                    M.Visible = true
                    M.ZIndex = 1
                    M.LayoutOrder = 0
                    M.Style = Enum.FrameStyle.Custom
                    M.Parent = Misc

                        local CheatName = Instance.new("TextLabel")
                        CheatName.Name = "CheatName"
                        CheatName.AnchorPoint = Vector2.new(0, 0)
                        CheatName.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.BackgroundTransparency = 12
                        CheatName.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.BorderSizePixel = 0
                        CheatName.Position = UDim2.new(0.011904762126505375, 0, -0.01505525317043066, 0)
                        CheatName.Rotation = 0
                        CheatName.Size = UDim2.new(0.2394559234380722, 0, 1, 0)
                        CheatName.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        CheatName.Visible = true
                        CheatName.ZIndex = 1
                        CheatName.LayoutOrder = 0
                        CheatName.Font = Enum.Font.SourceSans
                        CheatName.Text = "AutoSteal"
                        CheatName.TextColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.TextScaled = true
                        CheatName.TextSize = 14
                        CheatName.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.TextStrokeTransparency = 1
                        CheatName.TextWrapped = true
                        CheatName.TextXAlignment = Enum.TextXAlignment.Center
                        CheatName.TextYAlignment = Enum.TextYAlignment.Center
                        CheatName.Parent = M

                        local KeySteal = Instance.new("TextBox")
                        KeySteal.Name = "KeySteal"
                        KeySteal.AnchorPoint = Vector2.new(0, 0)
                        KeySteal.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                        KeySteal.BackgroundTransparency = 0.800000011920929
                        KeySteal.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        KeySteal.BorderSizePixel = 0
                        KeySteal.Position = UDim2.new(0.2789115607738495, 0, 0.19929662346839905, 0)
                        KeySteal.Rotation = 0
                        KeySteal.Size = UDim2.new(0.3401360511779785, 0, 0.5861665606498718, 0)
                        KeySteal.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        KeySteal.Visible = true
                        KeySteal.ZIndex = 1
                        KeySteal.LayoutOrder = 0
                        KeySteal.Font = Enum.Font.SourceSans
                        KeySteal.Text = ""
                        KeySteal.TextColor3 = Color3.fromRGB(255, 0, 4)
                        KeySteal.TextScaled = true
                        KeySteal.TextSize = 14
                        KeySteal.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        KeySteal.TextStrokeTransparency = 1
                        KeySteal.TextWrapped = true
                        KeySteal.TextXAlignment = Enum.TextXAlignment.Center
                        KeySteal.TextYAlignment = Enum.TextYAlignment.Center
                        KeySteal.ClearTextOnFocus = true
                        KeySteal.MultiLine = false
                        KeySteal.PlaceholderText = "KEY"
                        KeySteal.PlaceholderColor3 = Color3.fromRGB(207, 207, 207)
                        KeySteal.Parent = M

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                            UICorner.Parent = KeySteal

                        local AutoSteal = Instance.new("TextButton")
                        AutoSteal.Name = "AutoSteal"
                        AutoSteal.AnchorPoint = Vector2.new(0, 0)
                        AutoSteal.BackgroundColor3 = Color3.fromRGB(229, 0, 4)
                        AutoSteal.BackgroundTransparency = 0
                        AutoSteal.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        AutoSteal.BorderSizePixel = 0
                        AutoSteal.Position = UDim2.new(0.7363945841789246, 0, 0.2579132914543152, 0)
                        AutoSteal.Rotation = 0
                        AutoSteal.Size = UDim2.new(0.18027210235595703, 0, 0.48065656423568726, 0)
                        AutoSteal.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        AutoSteal.Visible = true
                        AutoSteal.ZIndex = 1
                        AutoSteal.LayoutOrder = 0
                        AutoSteal.Font = Enum.Font.SourceSans
                        AutoSteal.Text = "OFF"
                        AutoSteal.TextColor3 = Color3.fromRGB(255, 255, 255)
                        AutoSteal.TextScaled = true
                        AutoSteal.TextSize = 14
                        AutoSteal.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        AutoSteal.TextStrokeTransparency = 1
                        AutoSteal.TextWrapped = true
                        AutoSteal.TextXAlignment = Enum.TextXAlignment.Center
                        AutoSteal.TextYAlignment = Enum.TextYAlignment.Center
                        AutoSteal.AutoButtonColor = true
                        AutoSteal.Parent = M

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(5, 0)
                            UICorner.Parent = AutoSteal

                        local UICorner = Instance.new("UICorner")
                        UICorner.Name = "UICorner"
                        UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                        UICorner.Parent = M

                    local M = Instance.new("Frame")
                    M.Name = "M"
                    M.AnchorPoint = Vector2.new(0, 0)
                    M.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                    M.BackgroundTransparency = 0.800000011920929
                    M.BorderColor3 = Color3.fromRGB(0, 0, 0)
                    M.BorderSizePixel = 0
                    M.Position = UDim2.new(0, 0, 0, 0)
                    M.Rotation = 0
                    M.Size = UDim2.new(1, 0, 0.273341566324234, 0)
                    M.SizeConstraint = Enum.SizeConstraint.RelativeXY
                    M.Visible = true
                    M.ZIndex = 1
                    M.LayoutOrder = 0
                    M.Style = Enum.FrameStyle.Custom
                    M.Parent = Misc

                        local CheatName = Instance.new("TextLabel")
                        CheatName.Name = "CheatName"
                        CheatName.AnchorPoint = Vector2.new(0, 0)
                        CheatName.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.BackgroundTransparency = 12
                        CheatName.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.BorderSizePixel = 0
                        CheatName.Position = UDim2.new(0.011904762126505375, 0, -0.01505525317043066, 0)
                        CheatName.Rotation = 0
                        CheatName.Size = UDim2.new(0.2394559234380722, 0, 1, 0)
                        CheatName.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        CheatName.Visible = true
                        CheatName.ZIndex = 1
                        CheatName.LayoutOrder = 0
                        CheatName.Font = Enum.Font.SourceSans
                        CheatName.Text = "AutoGoal"
                        CheatName.TextColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.TextScaled = true
                        CheatName.TextSize = 14
                        CheatName.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.TextStrokeTransparency = 1
                        CheatName.TextWrapped = true
                        CheatName.TextXAlignment = Enum.TextXAlignment.Center
                        CheatName.TextYAlignment = Enum.TextYAlignment.Center
                        CheatName.Parent = M

                        local KeyAutoGoal = Instance.new("TextBox")
                        KeyAutoGoal.Name = "KeyAutoGoal"
                        KeyAutoGoal.AnchorPoint = Vector2.new(0, 0)
                        KeyAutoGoal.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                        KeyAutoGoal.BackgroundTransparency = 0.800000011920929
                        KeyAutoGoal.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        KeyAutoGoal.BorderSizePixel = 0
                        KeyAutoGoal.Position = UDim2.new(0.2789115607738495, 0, 0.19929662346839905, 0)
                        KeyAutoGoal.Rotation = 0
                        KeyAutoGoal.Size = UDim2.new(0.3401360511779785, 0, 0.5861665606498718, 0)
                        KeyAutoGoal.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        KeyAutoGoal.Visible = true
                        KeyAutoGoal.ZIndex = 1
                        KeyAutoGoal.LayoutOrder = 0
                        KeyAutoGoal.Font = Enum.Font.SourceSans
                        KeyAutoGoal.Text = ""
                        KeyAutoGoal.TextColor3 = Color3.fromRGB(255, 0, 4)
                        KeyAutoGoal.TextScaled = true
                        KeyAutoGoal.TextSize = 14
                        KeyAutoGoal.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        KeyAutoGoal.TextStrokeTransparency = 1
                        KeyAutoGoal.TextWrapped = true
                        KeyAutoGoal.TextXAlignment = Enum.TextXAlignment.Center
                        KeyAutoGoal.TextYAlignment = Enum.TextYAlignment.Center
                        KeyAutoGoal.ClearTextOnFocus = true
                        KeyAutoGoal.MultiLine = false
                        KeyAutoGoal.PlaceholderText = "KEY"
                        KeyAutoGoal.PlaceholderColor3 = Color3.fromRGB(207, 207, 207)
                        KeyAutoGoal.Parent = M

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                            UICorner.Parent = KeyAutoGoal

                        local AutoGoal = Instance.new("TextButton")
                        AutoGoal.Name = "AutoGoal"
                        AutoGoal.AnchorPoint = Vector2.new(0, 0)
                        AutoGoal.BackgroundColor3 = Color3.fromRGB(229, 0, 4)
                        AutoGoal.BackgroundTransparency = 0
                        AutoGoal.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        AutoGoal.BorderSizePixel = 0
                        AutoGoal.Position = UDim2.new(0.7363945841789246, 0, 0.2579132914543152, 0)
                        AutoGoal.Rotation = 0
                        AutoGoal.Size = UDim2.new(0.18027210235595703, 0, 0.48065656423568726, 0)
                        AutoGoal.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        AutoGoal.Visible = true
                        AutoGoal.ZIndex = 1
                        AutoGoal.LayoutOrder = 0
                        AutoGoal.Font = Enum.Font.SourceSans
                        AutoGoal.Text = "OFF"
                        AutoGoal.TextColor3 = Color3.fromRGB(255, 255, 255)
                        AutoGoal.TextScaled = true
                        AutoGoal.TextSize = 14
                        AutoGoal.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        AutoGoal.TextStrokeTransparency = 1
                        AutoGoal.TextWrapped = true
                        AutoGoal.TextXAlignment = Enum.TextXAlignment.Center
                        AutoGoal.TextYAlignment = Enum.TextYAlignment.Center
                        AutoGoal.AutoButtonColor = true
                        AutoGoal.Parent = M

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(5, 0)
                            UICorner.Parent = AutoGoal

                        local UICorner = Instance.new("UICorner")
                        UICorner.Name = "UICorner"
                        UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                        UICorner.Parent = M

                    local M = Instance.new("Frame")
                    M.Name = "M"
                    M.AnchorPoint = Vector2.new(0, 0)
                    M.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                    M.BackgroundTransparency = 0.800000011920929
                    M.BorderColor3 = Color3.fromRGB(0, 0, 0)
                    M.BorderSizePixel = 0
                    M.Position = UDim2.new(0, 0, 0, 0)
                    M.Rotation = 0
                    M.Size = UDim2.new(1, 0, 0.273341566324234, 0)
                    M.SizeConstraint = Enum.SizeConstraint.RelativeXY
                    M.Visible = true
                    M.ZIndex = 1
                    M.LayoutOrder = 0
                    M.Style = Enum.FrameStyle.Custom
                    M.Parent = Misc

                        local CheatName = Instance.new("TextLabel")
                        CheatName.Name = "CheatName"
                        CheatName.AnchorPoint = Vector2.new(0, 0)
                        CheatName.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.BackgroundTransparency = 12
                        CheatName.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.BorderSizePixel = 0
                        CheatName.Position = UDim2.new(0.011904762126505375, 0, -0.01505525317043066, 0)
                        CheatName.Rotation = 0
                        CheatName.Size = UDim2.new(0.2394559234380722, 0, 1, 0)
                        CheatName.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        CheatName.Visible = true
                        CheatName.ZIndex = 1
                        CheatName.LayoutOrder = 0
                        CheatName.Font = Enum.Font.SourceSans
                        CheatName.Text = "SpamTackle"
                        CheatName.TextColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.TextScaled = true
                        CheatName.TextSize = 14
                        CheatName.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.TextStrokeTransparency = 1
                        CheatName.TextWrapped = true
                        CheatName.TextXAlignment = Enum.TextXAlignment.Center
                        CheatName.TextYAlignment = Enum.TextYAlignment.Center
                        CheatName.Parent = M

                        local KeyTackle = Instance.new("TextBox")
                        KeyTackle.Name = "KeyTackle"
                        KeyTackle.AnchorPoint = Vector2.new(0, 0)
                        KeyTackle.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                        KeyTackle.BackgroundTransparency = 0.800000011920929
                        KeyTackle.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        KeyTackle.BorderSizePixel = 0
                        KeyTackle.Position = UDim2.new(0.2789115607738495, 0, 0.19929662346839905, 0)
                        KeyTackle.Rotation = 0
                        KeyTackle.Size = UDim2.new(0.3401360511779785, 0, 0.5861665606498718, 0)
                        KeyTackle.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        KeyTackle.Visible = true
                        KeyTackle.ZIndex = 1
                        KeyTackle.LayoutOrder = 0
                        KeyTackle.Font = Enum.Font.SourceSans
                        KeyTackle.Text = ""
                        KeyTackle.TextColor3 = Color3.fromRGB(255, 0, 4)
                        KeyTackle.TextScaled = true
                        KeyTackle.TextSize = 14
                        KeyTackle.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        KeyTackle.TextStrokeTransparency = 1
                        KeyTackle.TextWrapped = true
                        KeyTackle.TextXAlignment = Enum.TextXAlignment.Center
                        KeyTackle.TextYAlignment = Enum.TextYAlignment.Center
                        KeyTackle.ClearTextOnFocus = true
                        KeyTackle.MultiLine = false
                        KeyTackle.PlaceholderText = "KEY"
                        KeyTackle.PlaceholderColor3 = Color3.fromRGB(207, 207, 207)
                        KeyTackle.Parent = M

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                            UICorner.Parent = KeyTackle

                        local SpamTackle = Instance.new("TextButton")
                        SpamTackle.Name = "SpamTackle"
                        SpamTackle.AnchorPoint = Vector2.new(0, 0)
                        SpamTackle.BackgroundColor3 = Color3.fromRGB(229, 0, 4)
                        SpamTackle.BackgroundTransparency = 0
                        SpamTackle.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        SpamTackle.BorderSizePixel = 0
                        SpamTackle.Position = UDim2.new(0.7363945841789246, 0, 0.2579132914543152, 0)
                        SpamTackle.Rotation = 0
                        SpamTackle.Size = UDim2.new(0.18027210235595703, 0, 0.48065656423568726, 0)
                        SpamTackle.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        SpamTackle.Visible = true
                        SpamTackle.ZIndex = 1
                        SpamTackle.LayoutOrder = 0
                        SpamTackle.Font = Enum.Font.SourceSans
                        SpamTackle.Text = "OFF"
                        SpamTackle.TextColor3 = Color3.fromRGB(255, 255, 255)
                        SpamTackle.TextScaled = true
                        SpamTackle.TextSize = 14
                        SpamTackle.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        SpamTackle.TextStrokeTransparency = 1
                        SpamTackle.TextWrapped = true
                        SpamTackle.TextXAlignment = Enum.TextXAlignment.Center
                        SpamTackle.TextYAlignment = Enum.TextYAlignment.Center
                        SpamTackle.AutoButtonColor = true
                        SpamTackle.Parent = M

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(5, 0)
                            UICorner.Parent = SpamTackle

                        local UICorner = Instance.new("UICorner")
                        UICorner.Name = "UICorner"
                        UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                        UICorner.Parent = M

                local Player = Instance.new("ScrollingFrame")
                Player.Name = "Player"
                Player.AnchorPoint = Vector2.new(0, 0)
                Player.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                Player.BackgroundTransparency = 1
                Player.BorderColor3 = Color3.fromRGB(0, 0, 0)
                Player.BorderSizePixel = 0
                Player.Position = UDim2.new(0, 0, -1.2386657033403026e-07, 0)
                Player.Rotation = 0
                Player.Size = UDim2.new(1, 0, 0.98630291223526, 0)
                Player.SizeConstraint = Enum.SizeConstraint.RelativeXY
                Player.Visible = true
                Player.ZIndex = 1
                Player.LayoutOrder = 0
                Player.BottomImage = "rbxasset://textures/ui/Scroll/scroll-bottom.png"
                Player.CanvasPosition = Vector2.new(0, 0)
                Player.CanvasSize = UDim2.new(0, 0, 0, 0)
                Player.ElasticBehavior = Enum.ElasticBehavior.WhenScrollable
                Player.HorizontalScrollBarInset = Enum.ScrollBarInset.None
                Player.MidImage = "rbxasset://textures/ui/Scroll/scroll-middle.png"
                Player.ScrollBarImageColor3 = Color3.fromRGB(0, 0, 0)
                Player.ScrollBarImageTransparency = 0
                Player.ScrollBarThickness = 5
                Player.ScrollingDirection = Enum.ScrollingDirection.XY
                Player.ScrollingEnabled = true
                Player.TopImage = "rbxasset://textures/ui/Scroll/scroll-top.png"
                Player.VerticalScrollBarInset = Enum.ScrollBarInset.None
                Player.VerticalScrollBarPosition = Enum.VerticalScrollBarPosition.Right
                Player.Parent = Main

                    local UIListLayout = Instance.new("UIListLayout")
                    UIListLayout.Name = "UIListLayout"
                    UIListLayout.FillDirection = Enum.FillDirection.Vertical
                    UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
                    UIListLayout.Padding = UDim.new(0.009999999776482582, 0)
                    UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
                    UIListLayout.VerticalAlignment = Enum.VerticalAlignment.Top
                    UIListLayout.Wraps = false
                    UIListLayout.Parent = Player

                    local P = Instance.new("Frame")
                    P.Name = "P"
                    P.AnchorPoint = Vector2.new(0, 0)
                    P.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                    P.BackgroundTransparency = 0.800000011920929
                    P.BorderColor3 = Color3.fromRGB(0, 0, 0)
                    P.BorderSizePixel = 0
                    P.Position = UDim2.new(0, 0, 0, 0)
                    P.Rotation = 0
                    P.Size = UDim2.new(1, 0, 0.273341566324234, 0)
                    P.SizeConstraint = Enum.SizeConstraint.RelativeXY
                    P.Visible = true
                    P.ZIndex = 1
                    P.LayoutOrder = 0
                    P.Style = Enum.FrameStyle.Custom
                    P.Parent = Player

                        local UICorner = Instance.new("UICorner")
                        UICorner.Name = "UICorner"
                        UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                        UICorner.Parent = P

                        local CheatName = Instance.new("TextLabel")
                        CheatName.Name = "CheatName"
                        CheatName.AnchorPoint = Vector2.new(0, 0)
                        CheatName.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.BackgroundTransparency = 12
                        CheatName.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.BorderSizePixel = 0
                        CheatName.Position = UDim2.new(0.010204081423580647, 0, 0.12044202536344528, 0)
                        CheatName.Rotation = 0
                        CheatName.Size = UDim2.new(0.5268709063529968, 0, 0.7385697960853577, 0)
                        CheatName.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        CheatName.Visible = true
                        CheatName.ZIndex = 1
                        CheatName.LayoutOrder = 0
                        CheatName.Font = Enum.Font.SourceSans
                        CheatName.Text = "Fake Metavision"
                        CheatName.TextColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.TextScaled = true
                        CheatName.TextSize = 14
                        CheatName.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.TextStrokeTransparency = 1
                        CheatName.TextWrapped = true
                        CheatName.TextXAlignment = Enum.TextXAlignment.Left
                        CheatName.TextYAlignment = Enum.TextYAlignment.Center
                        CheatName.Parent = P

                        local Metavision = Instance.new("TextButton")
                        Metavision.Name = "Metavision"
                        Metavision.AnchorPoint = Vector2.new(0, 0)
                        Metavision.BackgroundColor3 = Color3.fromRGB(229, 0, 4)
                        Metavision.BackgroundTransparency = 0
                        Metavision.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        Metavision.BorderSizePixel = 0
                        Metavision.Position = UDim2.new(0.7363945841789246, 0, 0.2579132914543152, 0)
                        Metavision.Rotation = 0
                        Metavision.Size = UDim2.new(0.18027210235595703, 0, 0.48065656423568726, 0)
                        Metavision.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        Metavision.Visible = true
                        Metavision.ZIndex = 1
                        Metavision.LayoutOrder = 0
                        Metavision.Font = Enum.Font.SourceSans
                        Metavision.Text = "OFF"
                        Metavision.TextColor3 = Color3.fromRGB(255, 255, 255)
                        Metavision.TextScaled = true
                        Metavision.TextSize = 14
                        Metavision.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        Metavision.TextStrokeTransparency = 1
                        Metavision.TextWrapped = true
                        Metavision.TextXAlignment = Enum.TextXAlignment.Center
                        Metavision.TextYAlignment = Enum.TextYAlignment.Center
                        Metavision.AutoButtonColor = true
                        Metavision.Parent = P

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(5, 0)
                            UICorner.Parent = Metavision

                    local P = Instance.new("Frame")
                    P.Name = "P"
                    P.AnchorPoint = Vector2.new(0, 0)
                    P.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                    P.BackgroundTransparency = 0.800000011920929
                    P.BorderColor3 = Color3.fromRGB(0, 0, 0)
                    P.BorderSizePixel = 0
                    P.Position = UDim2.new(0, 0, 0, 0)
                    P.Rotation = 0
                    P.Size = UDim2.new(1, 0, 0.273341566324234, 0)
                    P.SizeConstraint = Enum.SizeConstraint.RelativeXY
                    P.Visible = true
                    P.ZIndex = 1
                    P.LayoutOrder = 0
                    P.Style = Enum.FrameStyle.Custom
                    P.Parent = Player

                        local UICorner = Instance.new("UICorner")
                        UICorner.Name = "UICorner"
                        UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                        UICorner.Parent = P

                        local CheatName = Instance.new("TextLabel")
                        CheatName.Name = "CheatName"
                        CheatName.AnchorPoint = Vector2.new(0, 0)
                        CheatName.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.BackgroundTransparency = 12
                        CheatName.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.BorderSizePixel = 0
                        CheatName.Position = UDim2.new(0.010204081423580647, 0, 0.12044202536344528, 0)
                        CheatName.Rotation = 0
                        CheatName.Size = UDim2.new(0.5268709063529968, 0, 0.7385697960853577, 0)
                        CheatName.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        CheatName.Visible = true
                        CheatName.ZIndex = 1
                        CheatName.LayoutOrder = 0
                        CheatName.Font = Enum.Font.SourceSans
                        CheatName.Text = "Fake Flow"
                        CheatName.TextColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.TextScaled = true
                        CheatName.TextSize = 14
                        CheatName.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.TextStrokeTransparency = 1
                        CheatName.TextWrapped = true
                        CheatName.TextXAlignment = Enum.TextXAlignment.Left
                        CheatName.TextYAlignment = Enum.TextYAlignment.Center
                        CheatName.Parent = P

                        local FakeFlow = Instance.new("TextButton")
                        FakeFlow.Name = "FakeFlow"
                        FakeFlow.AnchorPoint = Vector2.new(0, 0)
                        FakeFlow.BackgroundColor3 = Color3.fromRGB(229, 0, 4)
                        FakeFlow.BackgroundTransparency = 0
                        FakeFlow.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        FakeFlow.BorderSizePixel = 0
                        FakeFlow.Position = UDim2.new(0.7363945841789246, 0, 0.2579132914543152, 0)
                        FakeFlow.Rotation = 0
                        FakeFlow.Size = UDim2.new(0.18027210235595703, 0, 0.48065656423568726, 0)
                        FakeFlow.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        FakeFlow.Visible = true
                        FakeFlow.ZIndex = 1
                        FakeFlow.LayoutOrder = 0
                        FakeFlow.Font = Enum.Font.SourceSans
                        FakeFlow.Text = "OFF"
                        FakeFlow.TextColor3 = Color3.fromRGB(255, 255, 255)
                        FakeFlow.TextScaled = true
                        FakeFlow.TextSize = 14
                        FakeFlow.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        FakeFlow.TextStrokeTransparency = 1
                        FakeFlow.TextWrapped = true
                        FakeFlow.TextXAlignment = Enum.TextXAlignment.Center
                        FakeFlow.TextYAlignment = Enum.TextYAlignment.Center
                        FakeFlow.AutoButtonColor = true
                        FakeFlow.Parent = P

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(5, 0)
                            UICorner.Parent = FakeFlow

                    local P = Instance.new("Frame")
                    P.Name = "P"
                    P.AnchorPoint = Vector2.new(0, 0)
                    P.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                    P.BackgroundTransparency = 0.800000011920929
                    P.BorderColor3 = Color3.fromRGB(0, 0, 0)
                    P.BorderSizePixel = 0
                    P.Position = UDim2.new(0, 0, 0, 0)
                    P.Rotation = 0
                    P.Size = UDim2.new(1, 0, 0.273341566324234, 0)
                    P.SizeConstraint = Enum.SizeConstraint.RelativeXY
                    P.Visible = true
                    P.ZIndex = 1
                    P.LayoutOrder = 0
                    P.Style = Enum.FrameStyle.Custom
                    P.Parent = Player

                        local UICorner = Instance.new("UICorner")
                        UICorner.Name = "UICorner"
                        UICorner.CornerRadius = UDim.new(0.3499999940395355, 0)
                        UICorner.Parent = P

                        local CheatName = Instance.new("TextLabel")
                        CheatName.Name = "CheatName"
                        CheatName.AnchorPoint = Vector2.new(0, 0)
                        CheatName.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.BackgroundTransparency = 12
                        CheatName.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.BorderSizePixel = 0
                        CheatName.Position = UDim2.new(0.010204081423580647, 0, 0.12044202536344528, 0)
                        CheatName.Rotation = 0
                        CheatName.Size = UDim2.new(0.5268709063529968, 0, 0.7385697960853577, 0)
                        CheatName.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        CheatName.Visible = true
                        CheatName.ZIndex = 1
                        CheatName.LayoutOrder = 0
                        CheatName.Font = Enum.Font.SourceSans
                        CheatName.Text = "NoStun"
                        CheatName.TextColor3 = Color3.fromRGB(255, 255, 255)
                        CheatName.TextScaled = true
                        CheatName.TextSize = 14
                        CheatName.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        CheatName.TextStrokeTransparency = 1
                        CheatName.TextWrapped = true
                        CheatName.TextXAlignment = Enum.TextXAlignment.Left
                        CheatName.TextYAlignment = Enum.TextYAlignment.Center
                        CheatName.Parent = P

                        local NoStun = Instance.new("TextButton")
                        NoStun.Name = "NoStun"
                        NoStun.AnchorPoint = Vector2.new(0, 0)
                        NoStun.BackgroundColor3 = Color3.fromRGB(229, 0, 4)
                        NoStun.BackgroundTransparency = 0
                        NoStun.BorderColor3 = Color3.fromRGB(0, 0, 0)
                        NoStun.BorderSizePixel = 0
                        NoStun.Position = UDim2.new(0.7363945841789246, 0, 0.2579132914543152, 0)
                        NoStun.Rotation = 0
                        NoStun.Size = UDim2.new(0.18027210235595703, 0, 0.48065656423568726, 0)
                        NoStun.SizeConstraint = Enum.SizeConstraint.RelativeXY
                        NoStun.Visible = true
                        NoStun.ZIndex = 1
                        NoStun.LayoutOrder = 0
                        NoStun.Font = Enum.Font.SourceSans
                        NoStun.Text = "OFF"
                        NoStun.TextColor3 = Color3.fromRGB(255, 255, 255)
                        NoStun.TextScaled = true
                        NoStun.TextSize = 14
                        NoStun.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                        NoStun.TextStrokeTransparency = 1
                        NoStun.TextWrapped = true
                        NoStun.TextXAlignment = Enum.TextXAlignment.Center
                        NoStun.TextYAlignment = Enum.TextYAlignment.Center
                        NoStun.AutoButtonColor = true
                        NoStun.Parent = P

                            local UICorner = Instance.new("UICorner")
                            UICorner.Name = "UICorner"
                            UICorner.CornerRadius = UDim.new(5, 0)
                            UICorner.Parent = NoStun

                    local NoStun = Instance.new("TextButton")
                    NoStun.Name = "NoStun"
                    NoStun.AnchorPoint = Vector2.new(0, 0)
                    NoStun.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                    NoStun.BackgroundTransparency = 0.699999988079071
                    NoStun.BorderColor3 = Color3.fromRGB(0, 0, 0)
                    NoStun.BorderSizePixel = 0
                    NoStun.Position = UDim2.new(0, 0, 0.5281935930252075, 0)
                    NoStun.Rotation = 0
                    NoStun.Size = UDim2.new(1, 0, 0.16378416121006012, 0)
                    NoStun.SizeConstraint = Enum.SizeConstraint.RelativeXY
                    NoStun.Visible = true
                    NoStun.ZIndex = 1
                    NoStun.LayoutOrder = 0
                    NoStun.Font = Enum.Font.SourceSans
                    NoStun.Text = "TeamSelect"
                    NoStun.TextColor3 = Color3.fromRGB(255, 255, 255)
                    NoStun.TextScaled = true
                    NoStun.TextSize = 14
                    NoStun.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                    NoStun.TextStrokeTransparency = 1
                    NoStun.TextWrapped = true
                    NoStun.TextXAlignment = Enum.TextXAlignment.Center
                    NoStun.TextYAlignment = Enum.TextYAlignment.Center
                    NoStun.AutoButtonColor = true
                    NoStun.Parent = Player

                        local UICorner = Instance.new("UICorner")
                        UICorner.Name = "UICorner"
                        UICorner.CornerRadius = UDim.new(5, 0)
                        UICorner.Parent = NoStun

            local Options = Instance.new("ImageLabel")
            Options.Name = "Options"
            Options.AnchorPoint = Vector2.new(0, 0)
            Options.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
            Options.BackgroundTransparency = 1
            Options.BorderColor3 = Color3.fromRGB(0, 0, 0)
            Options.BorderSizePixel = 0
            Options.Position = UDim2.new(0.009764451533555984, 0, 0.1306057870388031, 0)
            Options.Rotation = 0
            Options.Size = UDim2.new(0.11950549483299255, 0, 0.8318583965301514, 0)
            Options.SizeConstraint = Enum.SizeConstraint.RelativeXY
            Options.Visible = true
            Options.ZIndex = 1
            Options.LayoutOrder = 0
            Options.Image = "rbxassetid://78746999303808"
            Options.ImageColor3 = Color3.fromRGB(255, 255, 255)
            Options.ImageTransparency = 0
            Options.ScaleType = Enum.ScaleType.Stretch
            Options.SliceCenter = "0, 0, 0, 0"
            Options.SliceScale = 1
            Options.TileSize = UDim2.new(1, 0, 1, 0)
            Options.Parent = Drag

                local UIListLayout = Instance.new("UIListLayout")
                UIListLayout.Name = "UIListLayout"
                UIListLayout.FillDirection = Enum.FillDirection.Vertical
                UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
                UIListLayout.Padding = UDim.new(0, 5)
                UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
                UIListLayout.VerticalAlignment = Enum.VerticalAlignment.Top
                UIListLayout.Wraps = false
                UIListLayout.Parent = Options

                local Misc = Instance.new("TextButton")
                Misc.Name = "Misc"
                Misc.AnchorPoint = Vector2.new(0, 0)
                Misc.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                Misc.BackgroundTransparency = 1
                Misc.BorderColor3 = Color3.fromRGB(0, 0, 0)
                Misc.BorderSizePixel = 0
                Misc.Position = UDim2.new(0, 0, 0, 0)
                Misc.Rotation = 0
                Misc.Size = UDim2.new(1, 0, 0.10992907732725143, 0)
                Misc.SizeConstraint = Enum.SizeConstraint.RelativeXY
                Misc.Visible = true
                Misc.ZIndex = 1
                Misc.LayoutOrder = 0
                Misc.Font = Enum.Font.DenkOne
                Misc.Text = "Misc"
                Misc.TextColor3 = Color3.fromRGB(255, 255, 255)
                Misc.TextScaled = true
                Misc.TextSize = 14
                Misc.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                Misc.TextStrokeTransparency = 1
                Misc.TextWrapped = true
                Misc.TextXAlignment = Enum.TextXAlignment.Center
                Misc.TextYAlignment = Enum.TextYAlignment.Center
                Misc.AutoButtonColor = true
                Misc.Parent = Options

                local Player = Instance.new("TextButton")
                Player.Name = "Player"
                Player.AnchorPoint = Vector2.new(0, 0)
                Player.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                Player.BackgroundTransparency = 1
                Player.BorderColor3 = Color3.fromRGB(0, 0, 0)
                Player.BorderSizePixel = 0
                Player.Position = UDim2.new(0, 0, 0, 0)
                Player.Rotation = 0
                Player.Size = UDim2.new(1, 0, 0.10992907732725143, 0)
                Player.SizeConstraint = Enum.SizeConstraint.RelativeXY
                Player.Visible = true
                Player.ZIndex = 1
                Player.LayoutOrder = 0
                Player.Font = Enum.Font.DenkOne
                Player.Text = "Player"
                Player.TextColor3 = Color3.fromRGB(255, 255, 255)
                Player.TextScaled = true
                Player.TextSize = 14
                Player.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                Player.TextStrokeTransparency = 1
                Player.TextWrapped = true
                Player.TextXAlignment = Enum.TextXAlignment.Center
                Player.TextYAlignment = Enum.TextYAlignment.Center
                Player.AutoButtonColor = true
                Player.Parent = Options

                local Other = Instance.new("TextButton")
                Other.Name = "Other"
                Other.AnchorPoint = Vector2.new(0, 0)
                Other.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                Other.BackgroundTransparency = 1
                Other.BorderColor3 = Color3.fromRGB(0, 0, 0)
                Other.BorderSizePixel = 0
                Other.Position = UDim2.new(0, 0, 0, 0)
                Other.Rotation = 0
                Other.Size = UDim2.new(1, 0, 0.10992907732725143, 0)
                Other.SizeConstraint = Enum.SizeConstraint.RelativeXY
                Other.Visible = true
                Other.ZIndex = 1
                Other.LayoutOrder = 0
                Other.Font = Enum.Font.DenkOne
                Other.Text = "Others"
                Other.TextColor3 = Color3.fromRGB(255, 255, 255)
                Other.TextScaled = true
                Other.TextSize = 14
                Other.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                Other.TextStrokeTransparency = 1
                Other.TextWrapped = true
                Other.TextXAlignment = Enum.TextXAlignment.Center
                Other.TextYAlignment = Enum.TextYAlignment.Center
                Other.AutoButtonColor = true
                Other.Parent = Options

            local UpBar = Instance.new("ImageLabel")
            UpBar.Name = "UpBar"
            UpBar.AnchorPoint = Vector2.new(0, 0)
            UpBar.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
            UpBar.BackgroundTransparency = 1
            UpBar.BorderColor3 = Color3.fromRGB(0, 0, 0)
            UpBar.BorderSizePixel = 0
            UpBar.Position = UDim2.new(-0.000653109687846154, 0, -0.09258980304002762, 0)
            UpBar.Rotation = 0
            UpBar.Size = UDim2.new(1.0006531476974487, 0, 0.20840924978256226, 0)
            UpBar.SizeConstraint = Enum.SizeConstraint.RelativeXY
            UpBar.Visible = true
            UpBar.ZIndex = 1
            UpBar.LayoutOrder = 0
            UpBar.Image = "rbxassetid://74857124519074"
            UpBar.ImageColor3 = Color3.fromRGB(255, 255, 255)
            UpBar.ImageTransparency = 0
            UpBar.ScaleType = Enum.ScaleType.Stretch
            UpBar.SliceCenter = "0, 0, 0, 0"
            UpBar.SliceScale = 1
            UpBar.TileSize = UDim2.new(1, 0, 1, 0)
            UpBar.Parent = Drag

                local GameTitle = Instance.new("TextLabel")
                GameTitle.Name = "GameTitle"
                GameTitle.AnchorPoint = Vector2.new(0, 0)
                GameTitle.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                GameTitle.BackgroundTransparency = 1
                GameTitle.BorderColor3 = Color3.fromRGB(0, 0, 0)
                GameTitle.BorderSizePixel = 0
                GameTitle.Position = UDim2.new(0.41813260316848755, 0, 0.25000056624412537, 0)
                GameTitle.Rotation = 0
                GameTitle.Size = UDim2.new(0.2746955454349518, 0, 0.44999998807907104, 0)
                GameTitle.SizeConstraint = Enum.SizeConstraint.RelativeXY
                GameTitle.Visible = true
                GameTitle.ZIndex = 1
                GameTitle.LayoutOrder = 0
                GameTitle.Font = Enum.Font.Unknown
                GameTitle.Text = "· Meta Lock"
                GameTitle.TextColor3 = Color3.fromRGB(255, 255, 255)
                GameTitle.TextScaled = true
                GameTitle.TextSize = 14
                GameTitle.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                GameTitle.TextStrokeTransparency = 1
                GameTitle.TextWrapped = true
                GameTitle.TextXAlignment = Enum.TextXAlignment.Center
                GameTitle.TextYAlignment = Enum.TextYAlignment.Center
                GameTitle.Parent = UpBar

                local Title = Instance.new("TextLabel")
                Title.Name = "Title"
                Title.AnchorPoint = Vector2.new(0, 0)
                Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                Title.BackgroundTransparency = 1
                Title.BorderColor3 = Color3.fromRGB(0, 0, 0)
                Title.BorderSizePixel = 0
                Title.Position = UDim2.new(0.017591340467333794, 0, 0.2000005692243576, 0)
                Title.Rotation = 0
                Title.Size = UDim2.new(0.2895805239677429, 0, 0.550000011920929, 0)
                Title.SizeConstraint = Enum.SizeConstraint.RelativeXY
                Title.Visible = true
                Title.ZIndex = 1
                Title.LayoutOrder = 0
                Title.Font = Enum.Font.Unknown
                Title.Text = "R.R.R HUB"
                Title.TextColor3 = Color3.fromRGB(255, 255, 255)
                Title.TextScaled = true
                Title.TextSize = 14
                Title.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
                Title.TextStrokeTransparency = 1
                Title.TextWrapped = true
                Title.TextXAlignment = Enum.TextXAlignment.Center
                Title.TextYAlignment = Enum.TextYAlignment.Center
                Title.Parent = UpBar

                    local UIStroke = Instance.new("UIStroke")
                    UIStroke.Name = "UIStroke"
                    UIStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual
                    UIStroke.Color = Color3.fromRGB(0, 0, 0)
                    UIStroke.LineJoinMode = Enum.LineJoinMode.Bevel
                    UIStroke.Thickness = 2.5
                    UIStroke.Transparency = 0
                    UIStroke.Enabled = true
                    UIStroke.Parent = Title

                local Minimize = Instance.new("ImageButton")
                Minimize.Name = "Minimize"
                Minimize.AnchorPoint = Vector2.new(0, 0)
                Minimize.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
                Minimize.BackgroundTransparency = 1
                Minimize.BorderColor3 = Color3.fromRGB(0, 0, 0)
                Minimize.BorderSizePixel = 0
                Minimize.Position = UDim2.new(0.886378288269043, 0, 0.3697664141654968, 0)
                Minimize.Rotation = 0
                Minimize.Size = UDim2.new(0.09472259879112244, 0, 0.25, 0)
                Minimize.SizeConstraint = Enum.SizeConstraint.RelativeXY
                Minimize.Visible = true
                Minimize.ZIndex = 1
                Minimize.LayoutOrder = 0
                Minimize.Image = "rbxassetid://138567149317610"
                Minimize.ImageColor3 = Color3.fromRGB(255, 255, 255)
                Minimize.ImageTransparency = 0
                Minimize.ScaleType = Enum.ScaleType.Stretch
                Minimize.SliceCenter = "0, 0, 0, 0"
                Minimize.SliceScale = 1
                Minimize.TileSize = UDim2.new(1, 0, 1, 0)
                Minimize.AutoButtonColor = true
                Minimize.Parent = UpBar

local UIS = game:GetService("UserInputService")

local frame = Drag -- << TROCA pelo seu frame principal

local dragging = false
local dragInput
local dragStart
local startPos

local function update(input)
	local delta = input.Position - dragStart
	frame.Position = UDim2.new(
		startPos.X.Scale,
		startPos.X.Offset + delta.X,
		startPos.Y.Scale,
		startPos.Y.Offset + delta.Y
	)
end

frame.InputBegan:Connect(function(input)
	if input.UserInputType == Enum.UserInputType.MouseButton1
		or input.UserInputType == Enum.UserInputType.Touch then

		dragging = true
		dragStart = input.Position
		startPos = frame.Position

		input.Changed:Connect(function()
			if input.UserInputState == Enum.UserInputState.End then
				dragging = false
			end
		end)
	end
end)

frame.InputChanged:Connect(function(input)
	if input.UserInputType == Enum.UserInputType.MouseMovement
		or input.UserInputType == Enum.UserInputType.Touch then

		dragInput = input
	end
end)

UIS.InputChanged:Connect(function(input)
	if input == dragInput and dragging then
		update(input)
	end
end)
